
class DataIngestionArtifact:...
class DataVAlidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainingArtifact:...
class ModelEvaluationArtifact:...
class ModelPublisherArtifact:...
