
class DataIngestionArtifact:
    feature_store_file_path:str
    train_file_path:str 
    test_file_path:str

class DataVAlidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainingArtifact:...
class ModelEvaluationArtifact:...
class ModelPublisherArtifact:...
